// Create a dictionary with all lyrics
// used the modern syntax because dicitonary variable value and key are same.
let lyrics = {
    bioject,
    bomdiggy,
    dancemonkey,
    panda,
    endsup,
    hotbox,
    eastside,
    // Classical
    allNight,
    nothingChange,
    thinkingoutloud,
    nothingStop,
    whitneyHL,
    //Country
    meanTobe,
    HotelC,
    rememberwhen,
    YouNotAlone,
    soledad,
    //Dance
    takitaki,
    sAndIKnow,
    partyRock,
    bumTam,
    TDrift,
    //Funk
    gLikeme,
    celebration,
    getDownonit,
    uptownFunk,
    rapperDe,
    //Hip Hop
    rockstar,
    panda,
    popStar,
    trapQueen,
    blueberry,
    //latin
    Danza,
    bailando,
    despacito,
    equis,
    radio,
    //Pop
    watermelon,
    yummy,
    whatGoes,
    roses,
    //rap
    smack,
    godzilla,
    oldTown,
    marmalade,
    thriftShop,
    //rock
    gRose,
    intheEnd,
    divide,
    numb,
    teenS
};